image: python:3.6

stages:
   - test
   # - deploy

before_script:
- apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev

testing:
    stage: test
    script:
    - pip install -r requirement-devel.txt
    - export MURIA_SETUP=$MURIA_TEST_INI_FILE
    - py.test
    only:
    - feature-init

# job produksi:
#     stage: deploy
#     script:
#     only:
#     - feature-init
