stages:
   - test
   - deploy

testing:
    image: python:3.6
    stage: test
    script:
    - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev
    - pip install -r requirement-devel.txt
    # somehow this will be passed as test has its own
    # internal setup defined
    - export MURIA_SETUP=$MURIA_TEST_INI_FILE
    - py.test
    when: manual
    only:
    - feature-init

uploading:
    image: alpine:latest
    stage: deploy
    script:
    - apk update && apk add openssh && apk add sshpass
    - ls -l ./muria/
    # since the hosting server use passenger phusion server
    - mv muria/wsgi.py muria/passenger_wsgi.py
    - ls -l ./muria/
    - export SSHPASS=$REMOTE_SCP_PASSWORD
    - echo $REMOTE_SCP_USERNAME:$REMOTE_SCP_TARGET_PATH
    - sshpass -e scp -v -o stricthostkeychecking=no -P 64000 -r ./muria/* $REMOTE_SCP_USERNAME:$REMOTE_SCP_TARGET_PATH
    when: manual
    only:
    - feature-init
